Split 0039_auto_20171208_1842 into 5 migrations to avoid postgres transaction issue
Migration was failing with

        django.db.utils.OperationalError: cannot ALTER TABLE "data_jobquestionnaire" because it has pending trigger events

Research suggested that this was due to schema and data migrations in a single transaction, so this one migration has been split on schema/data boundaries.