circle psycopg2==2.6.2 bug
Installing psycopg2 failes on circle due to postgres 10.0 version installed there.
```
Downloading psycopg2-2.6.2.tar.gz (376kB)
...
Error: could not determine PostgreSQL version from '10.0'
```
Bug Details: https://github.com/psycopg/psycopg2/issues/594
We had this issue with iMADS already: https://github.com/Duke-GCB/iMADS/issues/137